### ISSUE TITLE
Implement help center page

### ISSUE THREAD

**Issue by Oshioke-Salaki** [BlockheaderWeb3-Community/autoswappr-dapp#21]
Implement a pixel perfect help center page from the [FIGMA](https://www.figma.com/design/JW1DKwDBVJq97whSwlWDLS/Auto-swapper?node-id=282-1715&node-type=frame&t=tMxPcYhV9Bd5SNnM-0) design.

**Comment by SudiptaPaul-31** [comment]
Let me try this one!

**Comment by danielgwaza** [comment]
willing to apply my frontend skills to a real world project, time to build.

**Comment by Yunusabdul38** [comment]
Can I contribute to this one?

**Comment by danielgwaza** [comment]
I am a frontend developer, I want to work on this issue.
