### ISSUE TITLE
Implement documentation page

### ISSUE THREAD

**Issue by Oshioke-Salaki** [BlockheaderWeb3-Community/autoswappr-dapp#22]
Implement a pixel perfect documentation page from the [FIGMA](https://www.figma.com/design/JW1DKwDBVJq97whSwlWDLS/Auto-swapper?node-id=282-1715&node-type=frame&t=tMxPcYhV9Bd5SNnM-0) design.

**Comment by SudiptaPaul-31** [comment]
Can I take this issue

**Comment by Yunusabdul38** [comment]
I’d like to resolve this.

**Comment by ONEONUORA** [comment]
May i work on this issue, I am a full stack developer.

**Comment by Oshioke-Salaki** [comment]
gm @ONEONUORA any update on this??

**Comment by ONEONUORA** [comment]
gm @Oshioke-Salaki  will send a pr soon
