### ISSUE TITLE
Implement select base token page

### ISSUE THREAD

**Issue by Oshioke-Salaki** [BlockheaderWeb3-Community/autoswappr-dapp#3]
Implement a pixel perfect select base token page according to the [figma design](https://www.figma.com/design/JW1DKwDBVJq97whSwlWDLS/Auto-swapper?node-id=288-2290&node-type=frame&t=TD5fHZerbCxY8HMK-0)

**Comment by KodeSage** [comment]
May I take this issue on?


I'm a Software Engineer with over 4+ years of  demonstrable expertise across modern web and blockchain technologies. My tech stack centers on Next.js, TypeScript, React, and Node.js for web development and Solidity, and Cairo/Rust for blockchain solutions. 

What sets me apart is my proven track record on OnlyDust and external Projects like Passage, Stellar, etc. This extensive involvement reflects my ability to deliver quality solutions under tight deadlines while adapting to diverse project requirements. With my deep experience in hackathon environments, I bring both technical excellence and practical development skills to the table. I'm confident I can contribute meaningfully to pushing the boundaries of what's possible in blockchain development while maintaining a focus on user-centric solutions. 

 I'm excited to bring this experience and drive for innovation to your team. 

Implementation Plan:

Responsive Layout:
Develop a component structure that precisely matches the Figma design across different devices.
Pixel-Perfect Styling:
Implement exact styling (colors, spacing, typography, etc.) to ensure the UI is visually identical to the design.
Optimized Codebase:
Write clean, maintainable, and reusable code using best practices.
I estimate completing the task in 2.5 hours. This includes testing for responsiveness, ensuring compatibility across major browsers, and delivering high-quality, production-ready code.

**Comment by Yunusabdul38** [comment]
I'd love to work on this issue.
and make sure it meets the requirements

**Comment by abdegenius** [comment]
Is it okay if I tackle this? I can comfortably handle this issues

**Comment by martinvibes** [comment]
Can I take care of this issue?
i'm a frontend dev and a blockchain dev please kindly assign :)

**Comment by Tonyverse-ops** [comment]
Can I contribute to this one? I am new to onlydust and i would love an opprotunity to contribute and shwocase my skills
