### ISSUE TITLE
Implement select tokens page

### ISSUE THREAD

**Issue by Oshioke-Salaki** [BlockheaderWeb3-Community/autoswappr-dapp#4]
Implement a pixel perfect select tokens page from the [FIGMA](https://www.figma.com/design/JW1DKwDBVJq97whSwlWDLS/Auto-swapper?node-id=282-1715&node-type=frame&t=TD5fHZerbCxY8HMK-0)

**Comment by ikemHood** [comment]
would love to work on this as soon as ODHack resumes.

**Comment by Yunusabdul38** [comment]
I'd love to work on this issue.
and make sure it meets the requirements

**Comment by 0xdevcollins** [comment]
Could I take over this issue?

**Comment by josephchimebuka** [comment]
Hello I am Joseph I am a frontend developer and blockchain developer and I am also an active contributor here on only dust here is my profile https://app.onlydust.com/u/josephchimebuka. This is my first time to contribute to this repo ill appreciate the opportunity to contribute. this is a couple of frontend and blockchain projects i have built https://metacrypt.vercel.app/ https://mattedsgn.com/
May I pick this up?

**Comment by BrunoAmbricca** [comment]
I would like to work on this issue

**Comment by Benjtalkshow** [comment]
May I handle this issue?

**Comment by martinvibes** [comment]
Can I take care of this issue?
i'm a frontend dev and a blockchain dev please kindly assign :)

**Comment by CollinsC1O** [comment]
I’d like to help with this.

**Comment by Akshola00** [comment]
Can I attempt this issue?

**Comment by Akshola00** [comment]
hi im akinshola akinniyi, a fullstack and friontedn dev i would like to work on this issue. 
i would efficiently implement the select token page eta <1 day

**Comment by MullerTheScientist** [comment]
can i please address this issue

**Comment by Michaelkingsdev** [comment]
Can I be assigned to this?  I am an experienced frontend developer with 3 years of experience.

**Comment by Kaminar-i** [comment]
Can I take this issue?

**Comment by DanielEmmanuel1** [comment]
Could I be assigned to this?

I'm a frontend developer with sufficient experience in creating a pixel perfect UI replica
ETA: 48 hrs
