### ISSUE TITLE
Wallet Connection

### ISSUE THREAD

**Issue by Abeeujah** [BlockheaderWeb3-Community/autoswappr-dapp#41]
Wallet connection does not persist through page reloads.

**Description:**

When the page is reloaded, the connected wallet session is lost, requiring users to reconnect their wallets.

**Expected Behavior:**

Wallet connection should persist through page reloads for a seamless user experience.

**ETA**
This issue is expected to be completed within 2 days of assignment. Failure to create a pull request (or draft pull request) within the expected time will lead to being unassigned.

**Comment by jaykayudo** [comment]
@Abeeujah  Can i be assigned this issue?

I am a full stack software developer with ample experience in building innovative and scalable solutions. 
 If assigned, I will follow the contribution guideline accurately, resolve this issue and  open a PR within 3 days

**Comment by mimisavage** [comment]
Can I take care of this issue?

**Comment by OWK50GA** [comment]
Hi, I'm Wilfrid Okorie, a Frontend Web Developer and I'd like to take this issue.

My approach:
I will solve this issue by implementing a local storage for the last connected wallet
On reload, I would check if there is any wallet connection still contained in the local storage, and if there's one I'll reconnect that wallet, to improve user experience. 

Expect my first PR within 24 hours
May I take care of this?

**Comment by PedroCo3lho** [comment]
Hi @Abeeujah,
I’m looking to contribute in this OdHack, and I’d like to work on this issue. I have experience working with starknet-react package and StarknetWalletKit. Please let me know if I can take this on. Thank you!

**Comment by zintarh** [comment]
I’m interested in this one.
I'm a frontend developer 

To handle wallet connection persistence using `starknet-react`, I would utilize the `connect` and `disconnect` functions to manage wallet connections, store the last connected wallet ID in local storage when a user connects, and retrieve it on page load to automatically reconnect the wallet; I would also implement a useEffect hook to check local storage for the stored wallet ID and invoke the `connect` function with that ID, ensuring the wallet connection persists seamlessly through page reloads.

**Comment by Yunusabdul38** [comment]
can i work on this ?
i will implement a auto connect feature to the starknetProvider to persist user auth on page reload

**Comment by SudiptaPaul-31** [comment]
Would love to work on this issue 

I am a fullstack and blockchain developer having experience for more than 1.5 years and had worked on many projects from previous odhack my profile: (https://app.onlydust.com/u/SudiptaPaul-31)

**Comment by Supa-mega** [comment]
Mind if I take this issue?

**Comment by 0xdevcollins** [comment]
Can I handle this task?

**Comment by Joewizy** [comment]
Could I take a shot at this?

**Comment by ryzen-xp** [comment]
Hi, I am a proficient blockchain developer, expert in Cairo, Rust, Solidity, Aptos, and web development. I have contributed to projects like Chainevents and Arkprojects etc.

I can implement a solution to persist the wallet connection through page reloads, ensuring a seamless user experience. Please assign this issue to me.

Thank you!

**Comment by Benjtalkshow** [comment]
I am a Full Stack Developer with a strong background in blockchain and extensive experience in Next.js/React, TypeScript, and Rust. I’ve made over 49 contributions to over 17 projects in the OnlyDust ecosystem, solving complex issues and delivering efficient, scalable solutions.

I can handle this task.
ETA is 3days.

**Comment by martinvibes** [comment]
i'm a frontend dev and blockchain dev 
i would love to work on this and get it done asap
I’m interested in this one.
kindly assign

i have something like this many times on different merged projects

**Comment by JuanPabloRodriguezC** [comment]
Can I take this issue?

I am a computer engineering student with a lot knowledge on frontend development and recent knowledge on cairo. I would like to tackle this issue using zustand hook to store the wallet state including the connection status address and provider.

**Comment by SudiptaPaul-31** [comment]
Would love to work on this issue 

I am a fullstack and blockchain developer having experience for more than 1.5 years and had worked on many projects from previous odhack my profile: (https://app.onlydust.com/u/SudiptaPaul-31)

**Comment by MullerTheScientist** [comment]
I'd love to address this issue

**Comment by Akshola00** [comment]
Hello, I'm Akinshola Akinniyi, a smart contract developer with experience in both blockchain and frontend development. I gained a strong foundation in decentralized applications and have contributed to several projects on OnlyDust, focusing on smart contract development and user interface improvements.

I would be happy to help resolve the issue with wallet connection persistence. With my experience in working with wallet integrations and frontend frameworks, I’m confident I can implement a solution that ensures the wallet connection persists through page reloads, improving the user experience. Please assign me this task—I look forward to contributing to the project!

**Comment by Michaelkingsdev** [comment]
Hello @LazarusAA 
I am a frontend developer with 4 years of experience. I would really love to work on this task. Can it be assigned to me?

**Comment by ShantelPeters** [comment]
Can I jump on this task?

**Comment by Jagadeeshftw** [comment]
Hello, I’d love to work on this issue as I have strong experience with front-end development. Please assign this to me, and I’ll deliver an efficient and secure PR within 12-24 hours.

**Comment by omsant02** [comment]
I would like to solve this issue

My approach
1. Implementing localStorage to store wallet connection state
2. Adding a useEffect hook to check for stored connection on component mount
3. Updating the useAccount hook implementation to restore the session

ETA : 12 hrs
