### ISSUE TITLE
Select Base Token Page

### ISSUE THREAD

**Issue by Abeeujah** [BlockheaderWeb3-Community/autoswappr-dapp#42]
Insufficient negative space in Page layout causing content overlap.

**Description:**

The page lacks sufficient negative space, leading to the layout cropping into the page content.

**Expected Behavior:**

Add appropriate negative space to ensure a visually consistent and usable layout.

**ETA**
This issue is expected to be completed within 2 days of assignment. Failure to create a pull request (or draft pull request) within the expected time will lead to being unassigned.

**Comment by mimisavage** [comment]
Could I take over this issue?

**Comment by Benjtalkshow** [comment]
I am a Full Stack Developer with a strong background in blockchain and extensive experience in Next.js/React, TypeScript, and Rust. I’ve made over 49 contributions to over 17 projects in the OnlyDust ecosystem, solving complex issues and delivering efficient, scalable solutions.

I can handle this task.
ETA is 3days.

**Comment by ncoquelet** [comment]
Hey,

I'm a dev with 20 years of XP, super comfy with TypeScript, React/Next, Dapps, Prisma, CI/CD. I ship fast and high-quality stuff. Worked with AFK and GoStarkMe, check my GitHub profile for more details (got several hackathon prizes).
Currently doing Basecamp 11.

Down to handle this task.

**Comment by deeseeker** [comment]
Hello, I am Qudus Adeyemi (@deeseeker), a frontend developer with over two years of experience in React, TypeScript, and JavaScript. I am currently working on a social media app for African creators (https://app.myrevva.com/).

I have reviewed the requirements carefully and utilize my knowledge in css to make the design consistent and respnsive across devices. You can check out my portfolio for a sample of my work, such as https://logisfi-pro-app.vercel.app/, available on my GitHub.

I would love the opportunity to take on this issue.

**Comment by MullerTheScientist** [comment]
I'd love to Tackle this issue

**Comment by Michaelkingsdev** [comment]
Hello @LazarusAA 
I am a frontend developer with 4 years of experience. I would really love to work on this task. Can it be assigned to me?

**Comment by Pvsaint** [comment]
I’d love to work on this task please, I'm Victor Peter, a front-end and smart contract developer. I promise to write a pixel perfect code.

**Comment by therealemino** [comment]
Hi, I've over 4 years professional experience working on frontend applications (React, Vue, Next, Nuxt, TS). I've gone through the repository and Figma design. I believe this is an excellent first issue for me to contribute to. Can take on this task?

**Comment by ShantelPeters** [comment]
Can I take this from here?

**Comment by melnikga** [comment]
Can I contribute to this one?
Hi, my name is Georgiy, I'm a fullstack blockchain developer. I have extensive experience in developing tools for Starknet, and I've participated in almost all ODHacks, during which I worked on many projects. My OnlyDust profile: https://app.onlydust.com/u/melnikga

**Comment by Jagadeeshftw** [comment]
Hello, I’d love to work on this issue as I have strong experience with front-end development. Please assign this to me, and I’ll deliver an efficient and secure PR within 12-24 hours.

**Comment by omsant02** [comment]
I would like to take this issue

My approach to solve this issue
1. Adding margin-bottom to the main content container using Tailwind's mb utilities
2. Setting a min-height on the content area to prevent overlap

ETA : 6 hrs

**Comment by omsant02** [comment]
i have fixed the issues @Abeeujah ,
please review the pr and please let me know if any changes required
