### ISSUE TITLE
Select Tokens Page

### ISSUE THREAD

**Issue by Abeeujah** [BlockheaderWeb3-Community/autoswappr-dapp#43]
UI and layout inconsistencies.

1. **SVG Errors:** The following attributes need correction:
    - Replace stroke-linecap with its valid DOM variant strokeLinecap.
    - Replace stroke-linejoin with its valid DOM variant strokeLinejoin.

2. **Footer Negative Space:** Lack of negative space causes the footer to overlap with the content.

**Expected Behavior:**
- Correct SVG attributes to eliminate errors.
- Ensure sufficient negative space to prevent footer overlap.

**ETA**
This issue is expected to be completed within 2 days of assignment. Failure to create a pull request (or draft pull request) within the expected time will lead to being unassigned.

**Comment by gidson5** [comment]
May I pick this up? ETA 2days

**Comment by mimisavage** [comment]
Mind if I try this one?

**Comment by SYLVIANNORUKA** [comment]
Can I be assigned to this?I am a Front-end and smart contract developer. I am proficient in tailwind css, Next Js, Typescript, JavaScript, . I would love to contribute to this project.

**Comment by abdegenius** [comment]
Mind if I try this one?

**Comment by Agbeleshe** [comment]
About me
I am a diligent frontend developer with more than 3 years of working experience in creating responsive, pixel-perfect web and mobile applications with various libraries and frameworks, especially HTML Javascript React, Next.Js, TypeScript. And for styling tailwindCss, Vanila CSS, SCSS, mantime, etc.

My Approach in solving this issue
I will address the SVG errors by replacing stroke-linecap and stroke-linejoin with their valid DOM variants, strokeLinecap and strokeLinejoin. To resolve the footer overlap issue, I will ensure sufficient negative space is added, updating the layout to prevent the footer from overlapping with content and maintaining consistency across different screen sizes.

ETA
My estimated time to complete this task is within 1hour - 24hours.

**Comment by Kingsuite** [comment]
Mind if I try this one?

**Comment by Supa-mega** [comment]
Can I start working on this?

**Comment by 0xdevcollins** [comment]
I'd love to work on this!

**Comment by ryzen-xp** [comment]
Hi, I am a proficient blockchain developer, expert in Cairo, Rust, Solidity, Aptos, and web development. I have contributed to projects like Chainevents and Arkprojects etc .

I can fix the UI and layout inconsistencies by correcting the SVG attributes and ensuring sufficient negative space to prevent footer overlap. Please assign this issue to me.

Thank you!

**Comment by Benjtalkshow** [comment]
I am a Full Stack Developer with a strong background in blockchain and extensive experience in Next.js/React, TypeScript, and Rust. I’ve made over 49 contributions to over 17 projects in the OnlyDust ecosystem, solving complex issues and delivering efficient, scalable solutions.

I can handle this task.
ETA is 3days.

**Comment by Pvsaint** [comment]
I’d love to work on this task please, I'm Victor Peter, a front-end and smart contract developer. I promise to write a pixel perfect code.

**Comment by MullerTheScientist** [comment]
Would love to tackle this!

**Comment by ShantelPeters** [comment]
Let me try this one!

**Comment by Jagadeeshftw** [comment]
Hello, I’d love to work on this issue as I have strong experience with front-end development. Please assign this to me, and I’ll deliver an efficient and secure PR within 12-24 hours.

**Comment by omsant02** [comment]
I would like to take this issue 

Here's my implementation plan:

1. For the SVG attribute fixes, I'll update the tokens icons to use the correct DOM attributes:
- Replace stroke-linecap with strokeLinecap
- Replace stroke-linejoin with strokeLinejoin
This will resolve the React DOM warnings and ensure proper SVG rendering.

2. For the footer overlap, I'll implement proper margin/padding using Tailwind's spacing utilities in the main container component.

ETA : 1 day
