### ISSUE TITLE
Select Percentage Page

### ISSUE THREAD

**Issue by Abeeujah** [BlockheaderWeb3-Community/autoswappr-dapp#44]
Navbar overlaps page content.

**Description:**

There is not enough negative space at the top of the page content, causing the Navbar to overlap with the content.

**Expected Behavior:**

Add appropriate negative space to ensure the content is displayed without overlapping.

**ETA**
This issue is expected to be completed within 2 days of assignment. Failure to create a pull request (or draft pull request) within the expected time will lead to being unassigned.

**Comment by gidson5** [comment]
I’d like to help with this, i am frontend developer and new to odhacks

**Comment by mimisavage** [comment]
Could I take a shot at this?

**Comment by OWK50GA** [comment]
Can I take this from here?

**Comment by abdegenius** [comment]
Can I tackle this one?

**Comment by SudiptaPaul-31** [comment]
Would love to work on this issue 

I am a fullstack and blockchain developer having experience for more than 1.5 years and had worked on many projects from previous odhack my profile: (https://app.onlydust.com/u/SudiptaPaul-31)

**Comment by Supa-mega** [comment]
Could I take over this issue?

**Comment by Kachimercy1** [comment]
I'd love to work on this!

**Comment by ryzen-xp** [comment]
Hi, I am a proficient blockchain developer, expert in Cairo, Rust, Solidity, Aptos, and web development. I have contributed to projects like Chainevents and Arkprojects.

I can add the appropriate negative space at the top of the page content to prevent the Navbar from overlapping with the content. Please assign this issue to me.
Thank you!

**Comment by Benjtalkshow** [comment]
I am a Full Stack Developer with a strong background in blockchain and extensive experience in Next.js/React, TypeScript, and Rust. I’ve made over 49 contributions to over 17 projects in the OnlyDust ecosystem, solving complex issues and delivering efficient, scalable solutions.

I can handle this task.
ETA is 3days.

**Comment by emarc99** [comment]
Would love to tackle this!

**Comment by MullerTheScientist** [comment]
Would love to address this issue

**Comment by Michaelkingsdev** [comment]
Hello @LazarusAA 
I am a frontend developer with 4 years of experience. I would really love to work on this task. Can it be assigned to me?

**Comment by ShantelPeters** [comment]
Can I try solving this issue?

**Comment by melnikga** [comment]
Can I contribute to this one?
Hi, my name is Georgiy, I'm a fullstack blockchain developer. I have extensive experience in developing tools for Starknet, and I've participated in almost all ODHacks, during which I worked on many projects. My OnlyDust profile: https://app.onlydust.com/u/melnikga

**Comment by Jagadeeshftw** [comment]
Hello, I’d love to work on this issue as I have strong experience with front-end development. Please assign this to me, and I’ll deliver an efficient and secure PR within 12-24 hours.Is this issue still available?

**Comment by omsant02** [comment]
I would like to take this issue

I'll solve this by implementing padding-top using Tailwind CSS utility classes in the main container component of the Select Percentage page. 

I'll ensure the content has proper spacing from the navbar while maintaining responsiveness across different screen sizes. Since this is a layout issue, no additional state management or complex logic is needed - just proper CSS spacing.

ETA : 12 hrs

**Comment by SimplementeCao** [comment]
---

**Hey! I'm SimplementeCao 👋**  

I've contributed to several projects, including:  
- **Cairo Book**  
- **Starknet Book**  
- **Starknet Docs**  
- **Starknet Security Challenges Factory**  
- **Starkane**  
- **SocialSphere**  
- **SafeSwap**  
- **SafeTrustcr**  

Estimated time 24hs

You can learn more about my work through my [OnlyDust Profile](https://app.onlydust.com/u/SimplementeCao) and my [GitHub Profile](https://github.com/SimplementeCao).  

**🛠️ Plan to Solve the Issue:**  
1. **Analyze the Codebase:** Review its structure and functionality to understand the current implementation.  
2. **Understand the Issue:** Carefully read the problem description to clarify requirements.  
3. **Research & Plan:** Use provided resources and documentation for deeper insight.  
4. **Ask Questions:** Reach out in the relevant communication channels if any clarification is needed.  
5. **Submit a PR:** Implement the solution and submit a pull request for feedback.  

Let me know if I can start working on this! 🚀  

---

**Comment by princeibs** [comment]
@MullerTheScientist any update on this?

**Comment by princeibs** [comment]
Completed by #65

**Comment by princeibs** [comment]
Completed by #65
