### ISSUE TITLE
Activity Log Page

### ISSUE THREAD

**Issue by Abeeujah** [BlockheaderWeb3-Community/autoswappr-dapp#45]
UI improvements needed.

**Description:**
1. Footer cropping into page content due to lack of negative space.
2. Scrollbar style is not aligned with the application’s design.
3. Horizontal scrolling is missing, preventing users from viewing timestamps on smaller screens.
4. Div-based layout is less semantic; tables should be used instead for better accessibility.

**Expected Behavior:**
- Add sufficient negative space to prevent footer overlap.
- Style scrollbars to match the application’s design.
- Enable horizontal scrolling for timestamp visibility.
- Use tables instead of divs for a more semantic UI.

**ETA**
This issue is expected to be completed within 2 days of assignment. Failure to create a pull request (or draft pull request) within the expected time will lead to being unassigned.

**Comment by mimisavage** [comment]
May I be assigned to this?

**Comment by OWK50GA** [comment]
Hi, I'm Wilfrid Okorie, a Frontend Web Developer and I'd like to take this issue

Expect my first PR within 24 hours
I’m interested in this one.

**Comment by SYLVIANNORUKA** [comment]
Let me handle this issue!I am a Front-end and smart contract developer. I am proficient in tailwind css, Next Js, Typescript, JavaScript, . I would love to contribute to this project.

**Comment by abdegenius** [comment]
I’d like to work on this.

**Comment by Supa-mega** [comment]
Would love to tackle this!

**Comment by 0xdevcollins** [comment]
I'd like to take this issue.

**Comment by Benjtalkshow** [comment]
I am a Full Stack Developer with a strong background in blockchain and extensive experience in Next.js/React, TypeScript, and Rust. I’ve made over 49 contributions to over 17 projects in the OnlyDust ecosystem, solving complex issues and delivering efficient, scalable solutions.

I can handle this task.
ETA is 3days.

**Comment by Pvsaint** [comment]
I’d love to work on this task please, I'm Victor Peter, a frontend and smart contract developer. I promise to write a pixel perfect code.

**Comment by ncoquelet** [comment]
Hey,

I'm a dev with 20 years of XP, super comfy with TypeScript, React/Next, Dapps, Prisma, CI/CD. I ship fast and high-quality stuff. Worked with AFK and GoStarkMe, check my GitHub profile for more details (got several hackathon prizes).
Currently doing Basecamp 11.

Down to handle this task.

**Comment by jahrulezfrancis** [comment]
Hello @Abeeujah, I noticed a few UI improvements that are needed:

The footer is cropping into the content because there’s not enough negative space.
The scrollbar style doesn’t match the rest of the app.
Horizontal scrolling is missing, so users can’t view timestamps on smaller screens.
The layout uses divs, but tables would be more semantic and accessible.
I’ll fix these by adding some negative space, styling the scrollbars, enabling horizontal scrolling for timestamps, and switching to tables for better accessibility. I can get this done within 24 hours.

**Comment by Michaelkingsdev** [comment]
Hello @LazarusAA 
I am a frontend developer with 4 years of experience. I would really love to work on this task. Can it be assigned to me?

**Comment by MullerTheScientist** [comment]
Can I handle this task?

**Comment by kayceeDev** [comment]
Can I try solving this issue?

**Comment by therealemino** [comment]
Hi, I've over 4 years professional experience working on frontend applications (React, Vue, Next, Nuxt, TS). I've gone through the repository and Figma design. "I believe this is an excellent first issue for me to contribute to. Can take on this task?

**Comment by Emmanex01** [comment]
Can I handle this task?
I have 2+ years experience building as a Frontend developer.

**Comment by ShantelPeters** [comment]
Can I take care of this issue?

**Comment by Jagadeeshftw** [comment]
Hello, I’d love to work on this issue as I have strong experience with front-end development. Please assign this to me, and I’ll deliver an efficient and secure PR within 12-24 hours.

**Comment by omsant02** [comment]
i would like to take this issue

Here's my plan to address the issues:

1. Footer overlap: Will add proper margin spacing to prevent content overlap
2. Scrollbar styling: Will align scrollbar design with the app's theme
3. Horizontal scrolling: Will implement proper overflow handling for timestamps on all screen sizes
4. Layout structure: Will convert div-based layout to semantic tables for better accessibility

ETA : 1 day
