### ISSUE TITLE
Dex History Log Page

### ISSUE THREAD

**Issue by Abeeujah** [BlockheaderWeb3-Community/autoswappr-dapp#46]
UI improvements needed, similar to the Activity Log page.

**Description:**
1. Scrollbar style is not aligned with the application’s design.
2. Horizontal scrolling is missing, preventing users from viewing timestamps.
3. Div-based layout should be replaced with tables for semantic design.

**Expected Behavior:**
- Style scrollbars to match the application’s design.
- Enable horizontal scrolling for timestamp visibility.
- Use tables instead of divs for a more semantic UI.

**ETA**
This issue is expected to be completed within 2 days of assignment. Failure to create a pull request (or draft pull request) within the expected time will lead to being unassigned.

**Comment by gidson5** [comment]
Can I work on this, please? I'd follow the design guide to implement this ETA  2days

**Comment by mimisavage** [comment]
May I pick this up?

**Comment by Yunusabdul38** [comment]
Could I take over this issue?
i will make sure to implement a pixel perfect UI, enable the horizontal scrolling for timestamp visibility and also Use tables instead of divs for a more semantic UI

**Comment by SYLVIANNORUKA** [comment]
Could I take on this issue?I am a Front-end and smart contract developer. I am proficient in tailwind css, Next Js, Typescript, JavaScript, . I would love to contribute to this project.

**Comment by ONEONUORA** [comment]
Can i resolve this issue. I am a full stack developer. ETA 24hours

**Comment by abdegenius** [comment]
Can I contribute to this one?

**Comment by Supa-mega** [comment]
Is it okay if I tackle this?

**Comment by 0xdevcollins** [comment]
Can I be assigned to this?

**Comment by Pvsaint** [comment]
I’d love to work on this task please, I'm Victor Peter, a frontend and smart contract developer. I promise to write a pixel perfect code.

**Comment by martinvibes** [comment]
Would love to tackle this!

**Comment by Michaelkingsdev** [comment]
Hello @LazarusAA 
I am a frontend developer with 4 years of experience. I would really love to work on this task. Can it be assigned to me?

**Comment by Ekene001** [comment]
Hello I'm Ekene, a frontend and blockchain developer with proficiency in Solidity, typescript, Rust and react/Next js. This is my first time contributing to this repository, and I’m excited about the opportunity to collaborate and bring my skills to the table. 

please can i be be assigned to this task?

**Comment by therealemino** [comment]
Hi, I've over 4 years professional experience working on frontend applications (React, Vue, Next, Nuxt, TS). I've gone through the repository and Figma design. "I believe this is an excellent first issue for me to contribute to. Can take on this task?

**Comment by Emmanex01** [comment]
Can I work on this, please?
I have 2+ years experience building as a Frontend developer.

**Comment by ShantelPeters** [comment]
I'd like to take this issue.

**Comment by Levi-Ojukwu** [comment]
## About Me 
Hello, I am Levi.
I am a web3 full stack developer with expertise in blockchain technology and frontend engineering. I build on EVM compatible (Solidity) and Starknet (Cairo) blockchains.
In the blockchain domain, my expertise in solidity and Cairo has enabled me to design, develop, and deploy smart contracts on the Ethereum and Starknet based platforms, facilitating decentralized applications (dApps) that are revolutionizing industries. 

## Tackling This Issue
- To tackle this issue, first I will style the scrollbars to align with the application's design.
- I will enable and implement horizontal scrolling, to enable users view the timestamp.
- Then I will replace the dive-based layouts to tables for semantic design.

If this issue is assigned to me, I will ensure compliance with the team and follow the team's guideline.

## ETA - 24 hours

**Comment by Jagadeeshftw** [comment]
Hello, I’d love to work on this issue as I have strong experience with front-end development. Please assign this to me, and I’ll deliver an efficient and secure PR within 12-24 hours.

**Comment by omsant02** [comment]
i would like to take this issue

Here's how I plan to address the issues:

1. Scrollbar styling: Will update scrollbars to match the app's dark theme and design language
2. Horizontal scrolling: Will implement proper overflow handling to ensure timestamps are fully visible
3. Layout structure: Will convert the current div-based layout to semantic table structure for better organization

ETA : 1 day
