### ISSUE TITLE
Help Center Page

### ISSUE THREAD

**Issue by Abeeujah** [BlockheaderWeb3-Community/autoswappr-dapp#48]
Form and layout issues.

**Description:**
1. Attachments field uses the wrong input type.
2. No input validation for required fields.
3. Missing submit handler for the form.
4. Caret (Subject input field) lacks padding, causing it to appear cramped.

**Expected Behavior:**
- Use the correct input type for attachments.
- Implement input validation for required fields.
- Add a functional submit handler.
- Adjust caret padding using styles such as `border-r-8 border-bg`.

**ETA**
This issue is expected to be completed within 2 days of assignment. Failure to create a pull request (or draft pull request) within the expected time will lead to being unassigned.

**Comment by ONEONUORA** [comment]
Can I take this from here? I am a full stack developer. I am very experienced with form validation

**Comment by SYLVIANNORUKA** [comment]
May I handle this issue?I am a Front-end and smart contract developer. I am proficient in tailwind css, Next Js, Typescript, JavaScript, . I would love to contribute to this project.

**Comment by Pvsaint** [comment]
Please let me handle this issue, I'm Victor, a frontend and smart contract developer.
ETA 48hrs.

**Comment by Akshola00** [comment]
Pls i would like to work on this issue
I'm a frontend dev and smart contract dev and I'm confident I can handle this issue

**Comment by abdegenius** [comment]
Could I try solving this?

**Comment by No-bodyq** [comment]
May I handle this issue?

**Comment by SudiptaPaul-31** [comment]
Would love to work on this issue 

I am a fullstack and blockchain developer having experience for more than 1.5 years and had worked on many projects from previous odhack my profile: (https://app.onlydust.com/u/SudiptaPaul-31)

**Comment by mimisavage** [comment]
Would love to tackle this!

**Comment by Supa-mega** [comment]
Could I grab this task?

**Comment by Luluameh** [comment]
Hi, I’m a frontend developer with experience in TypeScript and form handling. I’ve reviewed the issue and am confident I can address the layout and functionality problems on the Help Center page.

Plan to Solve the Issue:

Update the attachments field to use the correct input type for file uploads (e.g., type="file").
Implement input validation for the required fields to ensure all necessary fields are completed before submission.
Add a submit handler to the form, ensuring the form data is correctly submitted and handled.
Adjust the padding for the caret in the Subject input field by using styles such as border-r-8 border-bg to improve the visual appearance and prevent it from appearing cramped.
Test the form to ensure proper validation, input handling, and styling are in place.
Estimated Completion Time: 1 day

**Comment by SudiptaPaul-31** [comment]
Would love to work on this issue

I'm a fullstack and blockchain developer with experience this field for more than 1.5 years and had worked on previous session of odhack my profile:(https://app.onlydust.com/u/SudiptaPaul-31)

**Comment by blessingbytes** [comment]
i would to tackle this issue

**Comment by Benjtalkshow** [comment]
I am a Full Stack Developer with a strong background in blockchain and extensive experience in Next.js/React, TypeScript, and Rust. I’ve made over 49 contributions to over 17 projects in the OnlyDust ecosystem, solving complex issues and delivering efficient, scalable solutions.

I can handle this task.
ETA is 3days.

**Comment by 0xdevcollins** [comment]
Can I be assigned this issue?

My Background
I am a Full Stack Blockchain Developer with proficiency in Solidity/Rust, Next.js, TypeScript, React, and Node.js. I've demonstrated my ability to adjust to a variety of requirements, perform well under pressure, and reliably produce user-centric blockchain solutions with 58 significant contributions spread over 17 OnlyDust projects.

**Comment by ryzen-xp** [comment]
Hi, I am a proficient blockchain developer, expert in Cairo, Rust, Solidity, Aptos, and web development. I have contributed to projects like Chainevents and Arkprojects.

I can address the form and layout issues by fixing the attachment input type, implementing input validation, adding a submit handler, and adjusting the caret padding for better appearance. Please assign this issue to me.

Thank you

**Comment by MullerTheScientist** [comment]
Can I work on this, please?

**Comment by Agbeleshe** [comment]
**About Me**  
I am a diligent frontend developer with more than 3 years of working experience in creating responsive, pixel-perfect web and mobile applications using various libraries and frameworks, especially HTML, JavaScript, React, Next.js, and TypeScript. For styling, I am skilled in Tailwind CSS, Vanilla CSS, SCSS, Mantine, and more.  

**My Approach to Solving This Issue**  
I will correct the attachments field by using the appropriate input type, implement input validation for required fields to ensure data integrity, and create a functional submit handler to process form submissions. Additionally, I will adjust the caret padding in the subject input field using styles like `border-r-8` and `border-bg` to improve its visual alignment and ensure a polished layout.  

**ETA**  
My estimated time to complete this task is within 1–24 hours.

**Comment by chigozzdevv** [comment]
Hello boss :)
It is me again! Can I contribute to this one?

**Comment by austineblaise** [comment]
I'm a frontend JavaScript/TypeScript Blockchain developer. I will fix the attachments input, add validation for required fields, make the submit button work, and adjust the padding in the Subject field. I'm excited to improve the form!

**Comment by therealemino** [comment]
Hi, I've over 4 years professional experience working on frontend applications (React, Vue, Next, Nuxt, TS). I've gone through the repository and Figma design. I believe this is an excellent first issue for me to contribute to. Can take on this task?

**Comment by Emmanex01** [comment]
Could I take a shot at this?
I have 2+ years experience building as a Frontend developer.

**Comment by ussyalfaks** [comment]
I would love to work on this. My name is Usman, and I have solid experience in JavaScript, TypeScript, and React. I'm confident I can contribute effectively to this task. This my portfolio https://usmanalfaki-1nwv.vercel.app/

**Comment by ShantelPeters** [comment]
Can I try solving this issue?

**Comment by melnikga** [comment]
Can I contribute to this one?
Hi, my name is Georgiy, I'm a fullstack blockchain developer. I have extensive experience in developing tools for Starknet, and I've participated in almost all ODHacks, during which I worked on many projects. My OnlyDust profile: https://app.onlydust.com/u/melnikga

**Comment by Jagadeeshftw** [comment]
Hello, I’d love to work on this issue as I have strong experience with front-end development. Please assign this to me, and I’ll deliver an efficient and secure PR within 12-24 hours.

**Comment by omsant02** [comment]
I would like to take this issue

Here's my proposed approach for each item:

1. For the attachments field, I'll implement the correct file input type with drag-and-drop functionality
2. I'll add proper input validation for the required email and subject fields using form validation
3. I'll implement the submit handler functionality for the form, including proper error handling
4. I'll fix the subject field padding by adding proper border-r-8 border-bg styling

ETA : 12 hrs

**Comment by No-bodyq** [comment]
Here is my profile https://app.onlydust.com/u/No-bodyq

> Quote reply
> Referenc
