### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by Abeeujah** [BlockheaderWeb3-Community/autoswappr-dapp#49]
Content and functionality issues.

**Description:**
1. Static Date/Time displayed.
2. Dead links in social icons, teams, and documentation.

**Expected Behavior:**
- Display dynamic Date/Time.
- Ensure all links are functional.

**ETA**
This issue is expected to be completed within 2 days of assignment. Failure to create a pull request (or draft pull request) within the expected time will lead to being unassigned.

**Comment by JosueBrenes** [comment]
## [FE]: Fix Content and Functionality Issues

Hi, I'm Josué Brenes and I'll be working on this issue.  
I'm a Dojo Coding member. ⛩️  

I estimate this will take 1 day to complete.

---

### Steps to Resolve

1. **Dynamic Date/Time Implementation**  
   - Identify where the static date/time is displayed in the codebase.
   - Replace the static value with dynamic content:
     - Use JavaScript's `Date` object or a library like `dayjs` or `date-fns` to display the current date and time dynamically.
     - Set an interval to update the time dynamically if necessary.
   - Ensure the format matches the application's design (e.g., `YYYY-MM-DD HH:mm`).

2. **Fix Dead Links**  
   - **Social Icons**:
     - Verify each social icon points to the correct URL (e.g., Twitter, LinkedIn).
     - Update or remove links if the corresponding social account does not exist.
   - **Teams and Documentation Links**:
     - Check if the provided links are valid routes or external URLs.
     - Update dead links to point to the correct routes or resources.
     - If no valid resource exists, coordinate with the relevant team to obtain the correct URLs.

3. **Test Functionality**  
   - **Date/Time**:
     - Confirm that the date/time displays dynamically and updates correctly without a page reload.
   - **Links**:
     - Test each link to ensure it navigates to the correct destination.
     - Verify functionality on various devices and browsers.

4. **Responsiveness and Accessibility**  
   - Ensure the date/time display and updated links work well on different screen sizes.  
   - Add ARIA labels to icons and links for improved accessibility.

5. **Finalize and Submit**  
   - Commit the changes to a branch named `feature/fix-content-links`.  
   - Open a pull request with details of the fixes applied.

---

**Comment by abdegenius** [comment]
Can I contribute to this one?

**Comment by ONEONUORA** [comment]
May I pick this up? I am very familiar with dynamic date and time rendering and routering. ETA 24hours

**Comment by No-bodyq** [comment]
Is it okay if I tackle this?

**Comment by SudiptaPaul-31** [comment]
Would love to work on this issue 

I am a fullstack and blockchain developer having experience for more than 1.5 years and had worked on many projects from previous odhack my profile: (https://app.onlydust.com/u/SudiptaPaul-31)

**Comment by PedroCo3lho** [comment]
Hello @Abeeujah,
I’m a full-stack developer with a solid understanding of TypeScript, Next.js, and TailwindCSS. The UI requirements and development flow are clear to me. I’m looking forward to your approval and would love to work on this issue.

**Comment by mimisavage** [comment]
I’d like to work on this.

**Comment by Supa-mega** [comment]
I'd like to take this issue.

**Comment by ryzen-xp** [comment]
Hi, I am a proficient blockchain developer, expert in Cairo, Rust, Solidity, Aptos, and web development. I have contributed to projects like Chainevents and Arkprojects.

I can fix the content and functionality issues by making the Date/Time dynamic and ensuring all links are functional. Please assign this issue to me.

Thank you!

**Comment by Benjtalkshow** [comment]
I am a Full Stack Developer with a strong background in blockchain and extensive experience in Next.js/React, TypeScript, and Rust. I’ve made over 49 contributions to over 17 projects in the OnlyDust ecosystem, solving complex issues and delivering efficient, scalable solutions.

I can handle this task.
ETA is 3days.

**Comment by 0xdevcollins** [comment]
Can I be assigned this issue?

My Background
I am a Full Stack Blockchain Developer with proficiency in Solidity/Rust, Next.js, TypeScript, React, and Node.js. I've demonstrated my ability to adjust to a variety of requirements, perform well under pressure, and reliably produce user-centric blockchain solutions with 58 significant contributions spread over 17 OnlyDust projects.

**Comment by BigBen-7** [comment]
Is this issue still available?
I could get this dynamically running, I would love for it to be assigned to me.

**Comment by Agbeleshe** [comment]
About me
I am a diligent frontend developer with more than 3 years of working experience in creating responsive, pixel-perfect web and mobile applications with various libraries and frameworks, especially HTML Javascript React, Next.Js, TypeScript. And for styling tailwindCss, Vanila CSS, SCSS, mantime, etc.

My Approach in solving this issue
I will first locate the footer component. 
Locate the statically displayed date and time. create a dynamic logic to render current date and time and lastly, identify and link social icons appropriately
ETA
My estimated time to complete this task is within 1hour - 24hours.

**Comment by emarc99** [comment]
Can I tackle this one? First time contributing. ETA 2 days and will test.

**Comment by MullerTheScientist** [comment]
Would love to address this issue

**Comment by Belloabraham121** [comment]
Hey! I'm Iteooluwakisi.
Member of Web3Bridge. I have contributed before to other projects like:
• CoinSafe
• Scaffold-ETH
• BuidlGuidl

I am a frontend developer, proficient in ReactJS/NextJS, TypeScript, Solidity, and Cairo.

Can I work on this issue?

Plan to Solve the Issue:

Study the codebase to understand the current structure and functionality.
Understand the problem that needs to be solved by thoroughly reading the issue details.
Leverage all provided resources within the issue to get a better grasp of the task at hand.
If I encounter roadblocks, I will ask questions ASAP in the relevant group/chat to move forward effectively.
I will open a PR and wait for your feedback.

**Comment by SimplementeCao** [comment]
---

### Hey! I'm *SimplementeCao*. 👋

I have contributed before to other projects like:

- `Cairo Book`
- `Starknet Book`
- `Starknet Docs`
- `Starknet Security Challenges Factory`
- `Starkane`

Can I work on this issue?

Check my OnlyDust, I've contributed to many projects: [OnlyDust Profile](https://app.onlydust.com/u/SimplementeCao), 
and my [GitHub](https://github.com/SimplementeCao)

---

### Plan to Solve the Issue:

1. **Analyze the codebase** to understand the current structure and functionality.
2. **Review the problem description** that needs to be solved by thoroughly reading the issue details.
3. **Leverage all provided resources** within the issue to get a better grasp of the task at hand.
4. If I face any challenge, I will **ask questions promptly** in the relevant support group or communication channel to move forward efficiently.
5. Once resolved, I will **open a PR** and wait for your feedback.

---

Let me know if I can start working on this! 🚀

---

**Comment by Michaelkingsdev** [comment]
Hello @LazarusAA 
I am a frontend developer with 4 years of experience. I would really love to work on this task. Can it be assigned to me?

**Comment by gregemax** [comment]
Could I be assigned to this issue? I have experience with frontend development using TypeScript and can address both the dynamic Date/Time display and fix the dead links in the Footer. I'm excited to contribute!

**Comment by chigozzdevv** [comment]
Can I start working on this?

**Comment by therealemino** [comment]
Hi, I've over 4 years professional experience working on frontend applications (React, Vue, Next, Nuxt, TS). I've gone through the repository and Figma design. I believe this is an excellent first issue for me to contribute to and I can handle the task

**Comment by Emmanex01** [comment]
May I take care of this?
I have 2+ years experience building as a Frontend developer.

**Comment by gidson5** [comment]
Hello,I’d love to work on this issue.

**Comment by ShantelPeters** [comment]
May I pick this up?

**Comment by davidmelendez** [comment]
Hi, my name is David, and I’m a member of the ⛩️ Dojo Coding community. I’m excited about contributing to this project. This would be my first contribution here; however, I’ve been studying Web3 extensively to specialize in this field, and I have 19 years of experience in Web2 as a full-stack developer.
While my experience has been mainly in enterprise development (such as SQL Server and Oracle integrations, .NET), I am currently focusing on emerging technologies like Web3. I firmly believe this is the future, and I’m committed to fully transitioning into this area.
I’m confident that my experience and motivation can bring value to this project.
Can I start working on it? Here are my profiles:
GitHub: davidmelendez (Melendez)
OnlyDust: davidmelendez - OnlyDust

Looking forward to your feedback! 😊

**Comment by lindsaymoralesb** [comment]
### About me
Hi! I'm Lindsay, a Software Engineer based in CR, I bring 4.5+ years of exp as a full stack, but I've been specializing as a frontend developer. And since I joined Dojo Coding community I've been immersing myself in the web3 world.
### How would I approach this issue?
First, I'll start by analizing how are current components structured to make sure the new ones stay consistent with the already implemented patterns.
After that I'll start creating the smallest dynamic/reusable components that I would need for this component (if any). Once all this smaller components are implemented, I'll continue with the integration of this footer component, always ensuring that both the small components and the big component itself remains responsive on all devices.

**Comment by melnikga** [comment]
Can I contribute to this one?
Hi, my name is Georgiy, I'm a fullstack blockchain developer. I have extensive experience in developing tools for Starknet, and I've participated in almost all ODHacks, during which I worked on many projects. My OnlyDust profile: https://app.onlydust.com/u/melnikga

**Comment by omsant02** [comment]
I would like to take this issue

i can see the link in the footer are dead and its not showing the current time
i will implement that it will show current time as per the location of the browser and make the links redirectable when clicked on  them

ETA : 6 hrs

**Comment by Nityam573** [comment]
Could I take a shot at this?

**Comment by Yunusabdul38** [comment]
Can I take this issue?

**Comment by SimplementeCao** [comment]
Implement in the documentation a section to clarify that it should work in the dev branch, and that Pull Requests should be directed to the dev branch, not to the main branch.

Hi, I'm Leandro, Front-end developer.
I would solve the problem first by reviewing the code, fix the paths/links or add if necessary and add Dynamic Date/Time.
Estimated delivery time: 20 hours.

I have previously collaborated in other projects such as:

Cairo Book
Starknet Book
Starknet Docs
Starknet Security Challenge Factory
Starkane
Can I work on this topic?

Check out my OnlyDust, I have contributed to many projects: OnlyDust profile
and my GitHub

**Comment by BrunoAmbricca** [comment]
I would like to work on this issue

**Comment by NueloSE** [comment]
I am an experienced frontend developer.
Would love to tackle this!

**Comment by Superior212** [comment]
Hey! I'm Superior,
I'm a member of BuidlGuidl and have contributed to various projects such as:
CoinSafe
Web3Bridge
GuildAudit
I haven’t contributed to any OnlyDust projects yet, but I’m eager to use my experience to make a strong impact on this task.
Plan to Solve the Issue:
Study the Codebase: I’ll review the existing structure and functionality to understand the current implementation.
Understand the Problem: I’ll carefully read the issue details to comprehend the task at hand fully.
Leverage Resources: I’ll utilize any provided resources or references within the issue to guide my solution.
Seek Clarifications: If I encounter challenges, I’ll ask questions in the Telegram group to ensure steady progress.
Submit PR: Once the solution is implemented, I’ll open a pull request and await your feedback.
I’m excited to contribute and am confident in my ability to solve this issue effectively!

**Comment by caxtonacollins** [comment]
Could I try solving this?

**Comment by DuendexCR** [comment]
Could I take over this issue?

**Comment by michojekunle** [comment]
Can I tackle this one?

**Comment by mimisavage** [comment]
Can I take care of this issue?

**Comment by drakkomaximo** [comment]
Hello, I’m part of Dojo Coding and I'm ready to contribute to your project.

How I Plan to Solve This:

To address the static Date/Time issue, I’ll implement a dynamic solution that pulls the current Date/Time from the system so that it updates in real time. For the dead links, I’ll go through each one (social icons, teams, and documentation) and make sure they point to the correct locations or replace them if necessary. This way, users will be able to access all content without running into dead ends.

Expected Outcome:

The Date/Time will be fully dynamic, updating based on the current system time. All links will be functional, ensuring a smooth user experience. I’ll aim to complete this within the next two days, and I’ll create a pull request once everything is fixed. If I don’t meet this timeframe, I understand I may be unassigned from the task.

**Comment by OWK50GA** [comment]
I’m interested in this one.
Hi, I'm Wilfrid Okorie, a Frontend Web Developer and I'd like to take this issue.

I have experience working with Dates in JavaScript/TypeScript, and I certainly have experience working in Next, React and Web 3 projects. 

My approach:
I will go to the component that renders the static time (hard-coded) and I will use JavaScript date methods to make this display dynamic. 
Next, I will go to the social links in the footer and ensure they are all functional. 
After this, I will test and/or build to make sure I don't break flow with my PR. 
Expect my first PR within 12 hours of assignments

**Comment by Meet2054** [comment]
Can I be assigned to this?

**Comment by Prosper1218** [comment]
i'm prosper williams. A frontend/Blockchain Developer. i have experience working with Nextjs & React.

can I fix this for you?
I'd love to contribute to this project.

**Comment by austineblaise** [comment]
I'm Austine, a frontend JavaScript/TypeScript Blockchain developer. I’d like to work on this issue by implementing dynamic Date/Time display and fixing the broken links. I’m confident in delivering the solution within the expected timeframe.

Looking forward to contributing!

**Comment by 3th-Enjay** [comment]
Let me handle this issue!

**Comment by vic-Gray** [comment]
Let me handle this issue!

**Comment by markdavid000** [comment]
### I would really love to work on this issue, I promise to deliver a job well done and within the time range, Thank you.

## About Me
I’m a blockchain and frontend developer and a Web3bridge Alumni of Cohort X, I'm passionate about creating decentralized applications. I have hands-on experience developing smart contracts on EVM-compatible blockchains using Solidity. I focus on building secure and efficient systems while crafting intuitive user interfaces to bridge the gap between complex blockchain technology and everyday users.

## Solution Plan
After carefully going through the codebase on GitHub,
- I will write a code to dynamically display the date and make the links functional in the `app/components/footer.tsx` file.
- I will maintain the brand color theme and project structure
- I will follow and maintain the codebase structure using TypeScript, Nextjs, TailwindCSS e.t.c
- I will ensure the design is responsive and works across all devices

## ETA
1 day
