### ISSUE TITLE
Implement the landing page

### ISSUE THREAD

**Issue by Oshioke-Salaki** [BlockheaderWeb3-Community/autoswappr-dapp#5]
Implement a pixel perfect landing page from the [FIGMA](https://www.figma.com/design/JW1DKwDBVJq97whSwlWDLS/Auto-swapper?node-id=282-1715&node-type=frame&t=tMxPcYhV9Bd5SNnM-0) design.

**Comment by Yunusabdul38** [comment]
I'd love to work on this issue.
and make sure it meets the requirements

**Comment by abdegenius** [comment]
I can comfortably handle this issues, i will replica the exact design and deliver clean and easy to maintain codebase

**Comment by 0xdevcollins** [comment]
I'd like to take this issue.

**Comment by josephchimebuka** [comment]
Hello I am Joseph I am a frontend developer and blockchain developer and I am also an active contributor here on only dust here is my profile https://app.onlydust.com/u/josephchimebuka. This is my first time to contribute to this repo ill appreciate the opportunity to contribute. this is a couple of frontend and blockchain projects i have built https://metacrypt.vercel.app/ https://mattedsgn.com/
May I pick this up?

**Comment by Pvsaint** [comment]
Hi, can I handle this issues please, I'm a frontend and smart contract developer with about 3 years experience in react js. If given this task, I promise to delver within 48hrs

**Comment by emarc99** [comment]
Can I tackle this one? As you from my recent repository commits in "no fail" project,
I design perfect landing using React/NextJs technologies.

**Comment by Psalmuel01** [comment]
I'm Samuel, a proficient web3 frontend developer with experience in ui design. I am that developer that totally obsesses over delivering pixel perfect screens. I am meticulous about it, and I work very fast as well. My frontend skills are excellent, and my codebase/screens clean.

I would love to contribute my expertise to this project. Kindly let me.

**Comment by Benjtalkshow** [comment]
I'd like to handle this task. 
I am a Full Stack Developer with a strong background in blockchain and extensive experience in Next.js/React, TypeScript, and Rust. I’ve made over 45 contributions to over 15 projects in the OnlyDust ecosystem, solving complex issues and delivering efficient, scalable solutions.

**Comment by josephpdf** [comment]
Hi! @Oshioke-Salaki
I'm Joseph Poveda, I'm a member of the Dojo Coding community.
A bit about my background is that I'm just starting out with Only Dust and I want to contribute as much as I can to the project. My knowledge of different programming languages ​​will allow me to better solve problems.
To solve this issue I will:
1. **Analyze the Figma Design:** Review the provided Figma design to identify key layout details, typography, and colors.
2. **Set Up the Environment:** Use a framework and maintainable development.
3. **Develop Components:** Break down the page into reusable components and implement responsive styles.
4. **Ensure Pixel Perfection:** Overlay the design for accuracy and make adjustments.
5. **Optimize:** Validate performance and responsiveness.

**Comment by martinvibes** [comment]
Can I take care of this issue?
i'm a frontend dev and a blockchain dev please kindly assign :)
