### ISSUE TITLE
NavBar

### ISSUE THREAD

**Issue by Abeeujah** [BlockheaderWeb3-Community/autoswappr-dapp#50]
Non-functional links.

**Description:**
1. Brand link is not functional.
2. Activity and Home links are dead.

**Expected Behavior:**

- Fix all dead links in the NavBar for smooth navigation.

**ETA**
This issue is expected to be completed within 2 days of assignment. Failure to create a pull request (or draft pull request) within the expected time will lead to being unassigned.

**Comment by JosueBrenes** [comment]
## [FE]: Fix Non-Functional Links in NavBar

Hi, I'm Josué Brenes and I'll be working on this issue.  
I'm a Dojo Coding member. ⛩️  

I estimate this will take less than 1 day to complete.

---

### Steps to Resolve

1. **Identify Dead Links**  
   - Review the `NavBarComponent.tsx` file in `src/components/ui` to locate the dead links:
     - **Brand Link**
     - **Activity Link**
     - **Home Link**

2. **Update Links**  
   - Replace placeholder or non-functional links with appropriate routes:
     - **Brand Link**: Should navigate to `/dashboard`.
     - **Activity Link**: Update to the corresponding route if it exists (e.g., `/activity`), or remove it if not applicable.
     - **Home Link**: Point to `/`.

3. **Validate Routes**  
   - Ensure all updated links correspond to existing routes in the application. If a route does not exist, coordinate with the backend or other team members to define it.

4. **Test Navigation**  
   - Verify that clicking each link navigates to the correct page without errors.  
   - Test links on various devices and screen sizes to ensure responsiveness.

5. **Finalize and Submit**  
   - Commit the changes to a branch named `feature/fix-navbar-links`.  
   - Open a pull request with details of the fixes applied.

---

**Comment by Shoetan** [comment]
I am Emmanuel returning contributor skilled in React,Tailwind CSS, TypeScript, Cairo and Redux, with experience contributing to open-source projects on only dust
 Recently contributed to Carbonable PR: https://github.com/Carbonable/contracts-watcher/pull/27   I’ll address this issue by delivering clean, efficient, and well-documented code.  Onlydust Profile: https://app.onlydust.com/u/Shoetan

**Comment by Agbeleshe** [comment]
About me
I am a diligent frontend developer with more than 3 years of working experience in creating responsive, pixel-perfect web and mobile applications with various libraries and frameworks, especially HTML Javascript React, Next.Js, TypeScript. And for styling tailwindCss, Vanila CSS, SCSS, mantime, etc.

My Approach in solving this issue
i will review and update NavBarComponent.tsx to fix dead links, ensuring proper routes are assigned, navigation is tested, and changes are committed with a detailed pull request.

ETA
My estimated time to complete this task is within 1hour - 24hours.

**Comment by abdegenius** [comment]
May I take this issue on?

**Comment by ONEONUORA** [comment]
Can i take up this issue. I will implement routing and make all the links functional. ETA 24 hours

**Comment by No-bodyq** [comment]
Is it okay if I take this?

**Comment by Shoetan** [comment]
Can I jump on this task?

I am Emmanuel returning contributor skilled in React,Tailwind CSS, TypeScript, Cairo and Redux, with experience contributing to open-source projects on only dust
 Recently contributed to Carbonable PR: https://github.com/Carbonable/contracts-watcher/pull/27   I’ll address this issue by delivering clean, efficient, and well-documented code.  Onlydust Profile: https://app.onlydust.com/u/Shoetan

**Comment by Iwueseiter** [comment]
Can I take care of this issue?
I'm a frontend and smart contract developer. I will implement this task by looking up the non-functional links on the nav bar and fixing them up.
This will be my first time contributing to this project.

**Comment by Agbeleshe** [comment]
About me
I am a diligent frontend developer with more than 3 years of working experience in creating responsive, pixel-perfect web and mobile applications with various libraries and frameworks, especially HTML Javascript React, Next.Js, TypeScript. And for styling tailwindCss, Vanila CSS, SCSS, mantime, etc.

My Approach in solving this issue
i will review and update NavBarComponent.tsx to fix dead links, ensuring proper routes are assigned, navigation is tested, and changes are committed with a detailed pull request.

ETA
My estimated time to complete this task is within 1hour - 24hours.

**Comment by 0xdevcollins** [comment]
Can I be assigned this issue?

My Background
I am a Full Stack Blockchain Developer with proficiency in Solidity/Rust, Next.js, TypeScript, React, and Node.js. I've demonstrated my ability to adjust to a variety of requirements, perform well under pressure, and reliably produce user-centric blockchain solutions with 58 significant contributions spread over 17 OnlyDust projects.

**Comment by ryzen-xp** [comment]
Hi, I am a proficient blockchain developer, expert in Cairo, Rust, Solidity, Aptos, and web development. I have contributed to projects like Chainevents and Arkprojects.

I can fix the dead links in the NavBar to ensure smooth navigation and a better user experience. Please assign this issue to me.

Thank you!

**Comment by Pvsaint** [comment]
I’d love to work on this task please, I'm Victor Peter, a frontend and smart contract developer. I promise to write a pixel perfect code.

**Comment by Yunusabdul38** [comment]
May I be assigned to this?

**Comment by BigBen-7** [comment]
I'd be happy to do this.

**Comment by SudiptaPaul-31** [comment]
Would love to work on this issue 

I am a fullstack and blockchain developer having experience for more than 1.5 years and had worked on many projects from previous odhack my profile: (https://app.onlydust.com/u/SudiptaPaul-31)

**Comment by mimisavage** [comment]
Would love to tackle this!

**Comment by MullerTheScientist** [comment]
I’d love to work on this task please

**Comment by gregemax** [comment]
Can I tackle this issue? I have experience in frontend development using TypeScript, and I can ensure that all the dead links in the NavBar are fixed for smooth navigation. Looking forward to contributing!

**Comment by Supa-mega** [comment]
Can I handle this task?

**Comment by austineblaise** [comment]
I will fix the dead links in the NavBar (Brand, Activity, and Home links) to ensure smooth navigation. I'll make sure the links are functional and properly redirect to the right pages. Looking forward to contributing to the project!

**Comment by chigozzdevv** [comment]
I'd love to work on this!

**Comment by ussyalfaks** [comment]
I would love to work on this. My name is Usman, and I have solid experience in JavaScript, TypeScript, and React. I'm confident I can contribute effectively to this task. This my portfolio https://usmanalfaki-1nwv.vercel.app/

**Comment by ShantelPeters** [comment]
May I handle this issue?

**Comment by omsant02** [comment]
i would like to take this issue

i can see currently the elements in the navbar doesnt redirect to anywhere,
i will fix them by making them them to redirect on the particular route when clicked on them

ETA : 6 hrs

**Comment by Jagadeeshftw** [comment]
Hello, I’d love to work on this issue as I have strong experience with front-end development. Please assign this to me, and I’ll deliver an efficient and secure PR within 12-24 hours.

**Comment by SimplementeCao** [comment]
Implement in the documentation a section to clarify that it should work in the dev branch, and that Pull Requests should be directed to the dev branch, not to the main branch.

Hi, I'm Leandro, Front-end developer.
I would solve the problem first by reviewing the code, fix the paths/links or add if necessary.
Estimated delivery time: 15 hours.

I have previously collaborated in other projects such as:

Cairo Book
Starknet Book
Starknet Docs
Starknet Security Challenge Factory
Starkane
Can I work on this topic?

Check out my OnlyDust, I have contributed to many projects: OnlyDust profile
and my GitHub

**Comment by Jayrodri088** [comment]
I’m excited about the opportunity to contribute to the Autoswappr project by addressing the non-functional links in the NavBar. With over three years of experience working in TypeScript, React, and Next.js, I understand how critical seamless navigation is to a polished user experience. Fixing the Brand, Activity, and Home links is a small but essential step toward ensuring the application remains user-friendly and professional.

To solve this, I’ll start by carefully reviewing the existing code to pinpoint where the links are failing, whether it’s due to incorrect routing or placeholder URLs. I’ll ensure that each link navigates to the intended destinations, like /dashboard for the Brand link and / for the Home link, while collaborating with the team if new routes need to be defined. Beyond simply fixing the links, I’ll also validate the updates by testing them across different devices and browsers to ensure responsiveness and compatibility.

I’m confident this task can be completed within one day, and I’d love to help make Autoswappr’s navigation as smooth as its design. I’m ready to dive in and submit a clear, detailed pull request as soon as the fixes are implemented. Thanks for considering my application!

Best regards,
John Asogwa
