### ISSUE TITLE
Overview Page

### ISSUE THREAD

**Issue by Abeeujah** [BlockheaderWeb3-Community/autoswappr-dapp#52]
Implement the `overview` page, make sure it's mobile responsive as well.

**Description:**

[Desktop View](https://www.figma.com/design/JW1DKwDBVJq97whSwlWDLS/Auto-swapper?node-id=356-11118&node-type=frame&t=I0aoi95acvIs1Imm-0)
[Mobile View](https://www.figma.com/design/JW1DKwDBVJq97whSwlWDLS/Auto-swapper?node-id=627-1729&node-type=frame&t=I0aoi95acvIs1Imm-0)

**Expected Behavior:**

Develop the Overview page based on the provided design.

**ETA**
This issue is expected to be completed within 2 days of assignment. Failure to create a pull request (or draft pull request) within the expected time will lead to being unassigned.

**Comment by SudiptaPaul-31** [comment]
Would love to work on this issue

I am a fullstack and blockchain developer having experience for more than 1.5 years and had worked on many projects from previous odhack my profile: (https://app.onlydust.com/u/SudiptaPaul-31)

**Comment by Tzienom** [comment]
Hi. I would love to work on this issue.

**Comment by blessingbytes** [comment]
i would love to tackle this issue

**Comment by starknetbrother** [comment]
May I take care of this?

**Comment by Iwueseiter** [comment]
Could I take over this issue?
I'm a frontend and smartcontract developer. I'm proficient with frontend libraries and I will implement this task as expected.

**Comment by Benjtalkshow** [comment]
I am a Full Stack Developer with a strong background in blockchain and extensive experience in Next.js/React, TypeScript, and Rust. I’ve made over 49 contributions to over 17 projects in the OnlyDust ecosystem, solving complex issues and delivering efficient, scalable solutions.

I can handle this task.
ETA is 3days.

**Comment by abdegenius** [comment]
Can I take care of this issue?

**Comment by Pvsaint** [comment]
I’d love to work on this task please, I'm Victor Peter, a frontend and smart contract developer. I promise to write a pixel perfect code.

**Comment by jahrulezfrancis** [comment]
I can implement the Overview page based on the design you’ve provided, ensuring it’s fully mobile-responsive as well. I’ll make sure it looks great on both desktop and mobile views. Let me know if there are any additional details you'd like me to include. With all the information I need being provided, I can complete the design within 24 hours.

**Comment by martinvibes** [comment]
i'm a frontend dev and blockchain dev 
i would love to work on this and get it done asap
I’m interested in this one.
kindly assign

**Comment by Agbeleshe** [comment]
About me
I am a diligent frontend developer with more than 3 years of working experience in creating responsive, pixel-perfect web and mobile applications with various libraries and frameworks, especially HTML Javascript React, Next.Js, TypeScript. And for styling tailwindCss, Vanila CSS, SCSS, mantime, etc.

My Approach

analyse the design and create a pixel-perfect representation of the design. 

ETA
My estimated time to complete this task is within 1hour - 24hours.

**Comment by Ekene001** [comment]
Hello I'm Ekene, a frontend and blockchain developer, and I’m new to the OnlyDust platform. This is my first time contributing to this repository, and I’m excited about the opportunity to collaborate and bring my skills to the table.

please can i be assigned to this task?

**Comment by PedroCo3lho** [comment]
Can I work on this? I’m a full-stack developer with experience working with Next.js and TailwindCSS.
By reviewing the project code base I will be implementing the Overview Page using the the UI packages already implemented (HeadlessUI and FramerMotion) to ensure the code standard through the repo and good UI/UX to the user.
I’m looking forward to your approval and would love to work on this issue.

**Comment by Awointa** [comment]
Can I try solving this issue?

**Comment by ncoquelet** [comment]
Hey,

I'm a dev with 20 years of XP, super comfy with TypeScript, React/Next, Dapps, Prisma, CI/CD. I ship fast and high-quality stuff. Worked with AFK and GoStarkMe, check my GitHub profile for more details (got several hackathon prizes).
Currently doing Basecamp 11.

Down to handle this task.

**Comment by MullerTheScientist** [comment]
I'd love to address this issue

**Comment by mimisavage** [comment]
Is this issue still available?

**Comment by Akshola00** [comment]
can i work on this
im confident I can handle this issue

**Comment by deeseeker** [comment]
Hello, I am Qudus Adeyemi (@deeseeker), a frontend developer with over two years of experience in React, TypeScript, and JavaScript. I am currently working on a social media app for African creators (https://app.myrevva.com/).

I have reviewed the requirements carefully and will convert the designs with great attention to detail.  You can check out my portfolio for a sample of my work, such as https://logisfi-pro-app.vercel.app/, available on my GitHub.

I would love the opportunity to take on this issue.

**Comment by Michaelkingsdev** [comment]
Hello @LazarusAA 
I am a frontend developer with 4 years of experience. I would really love to work on this task. Can it be assigned to me?

**Comment by gregemax** [comment]
Could I be assigned to this issue? I have experience with frontend development using TypeScript, and I ensure responsiveness for both desktop and mobile views. I'm eager to contribute and bring this design to life.

**Comment by Supa-mega** [comment]
I'd like to take this issue.

**Comment by Bran18** [comment]
Hello Team,

My name is Brandon Andrey Fernandez, and I am part of the Dojo Coding Community ⛩️💻 and https://bitcash.org/en. I’m excited about the opportunity to contribute to your project during Only Dust Hackathon #12! 🚀

I am a full-stack developer with experience in Web3 and blockchain technologies, particularly in projects involving smart contracts, AI integration, and decentralized solutions. I have worked on a large number of web3 projects and solutions as for example: 

https://masterbots.ai/
https://bitlauncher.ai/en

I am interested in this specific issue because it combines my passions: blockchain, AI technology, and modern web development. I am motivated by the opportunity to improve my skills and contribute to the project. I have participated in hackathons like ODH and other web2 based hackathons.

During the hackathon, I can dedicate approximately 5h min hours per day to working on this issue. I am committed to active collaboration, delivering high-quality code, and maintaining open communication with the team.

You can find my profiles and links here:

• GitHub: https://github.com/Bran18?tab=repositories
• OnlyDust: https://app.onlydust.com/u/Bran18
• X: https://x.com/branfdez_18
• LinkedIn: https://www.linkedin.com/in/brandonfdez18/

Thank you for considering my application. Please let me know if you have any questions or need any additional information.

**Comment by Belloabraham121** [comment]
Hey! I'm Iteooluwakisi.
Member of Web3Bridge. I have contributed before to other projects like:
• CoinSafe
• Scaffold-ETH
• BuidlGuidl

I am a frontend developer, proficient in ReactJS/NextJS, TypeScript, Solidity, and Cairo.

Can I work on this issue?

Plan to Solve the Issue:

Study the codebase to understand the current structure and functionality.
Understand the problem that needs to be solved by thoroughly reading the issue details.
Leverage all provided resources within the issue to get a better grasp of the task at hand.
If I encounter roadblocks, I will ask questions ASAP in the relevant group/chat to move forward effectively.
I will open a PR and wait for your feedback.

**Comment by austineblaise** [comment]
As a frontend JavaScript/TypeScript developer, I will create the Overview page based on the provided design. I will ensure it is mobile-responsive, so it works well on both desktop and mobile devices. I'm excited to bring this to life and work with your team!

**Comment by SudiptaPaul-31** [comment]
Would love to work on this issue

I am a fullstack and blockchain developer having experience for more than 1.5 years and had worked on many projects from previous odhack my profile: (https://app.onlydust.com/u/SudiptaPaul-31)

**Comment by chigozzdevv** [comment]
Hello, good day :)
Please can I take care of this issue?

**Comment by therealemino** [comment]
May I handle this issue?

**Comment by kayceeDev** [comment]
May I take care of this?

**Comment by 7-falseparfait** [comment]
Could I take over this issue?

**Comment by gidson5** [comment]
Hy, please Can I take on this issue?

**Comment by ussyalfaks** [comment]
I would love to work on this. My name is Usman, and I have solid experience in JavaScript, TypeScript, and React. I'm confident I can contribute effectively to this task. This my portfolio https://usmanalfaki-1nwv.vercel.app/

**Comment by Luluameh** [comment]
Let me handle this issue!

**Comment by markdavid000** [comment]
## About Me
I’m a blockchain and frontend developer passionate about creating decentralized applications. I have hands-on experience developing smart contracts on EVM-compatible blockchains using Solidity. I focus on building secure and efficient systems while crafting intuitive user interfaces to bridge the gap between complex blockchain technology and everyday users.

## Solution Plan
After carefully going through the codebase on GitHub and design,
- I will write the code to implement the Overview Page following the design.
- I will maintain the brand color theme and project structure
- I will follow and maintain the codebase structure using TypeScript, Nextjs, TailwindCSS e.t.c
- I will ensure the design is responsive and works across all devices

## ETA
10 Hours

**Comment by akintola4** [comment]
I’m interested in this one and i have gone through the figma file for this and i know i would be a able to do this within the specific time frame given to me

**Comment by melnikga** [comment]
Can I contribute to this one?
Hi, my name is Georgiy, I'm a fullstack blockchain developer. I have extensive experience in developing tools for Starknet, and I've participated in almost all ODHacks, during which I worked on many projects. My OnlyDust profile: https://app.onlydust.com/u/melnikga

**Comment by omsant02** [comment]
i would like to take this issue

i will create a new page that is "Overview", i will implement the ui that i can see in the figma design that is i will create a table where the (from, to , percentage, Autoswapper) columns

ETA : 6 hrs

**Comment by Jagadeeshftw** [comment]
Hello, I’d love to work on this issue as I have strong experience with front-end development. Please assign this to me, and I’ll deliver an efficient and secure PR within 12-24 hours.

**Comment by Nityam573** [comment]
Could I grab this task?
