### ISSUE TITLE
Implement select percentage page

### ISSUE THREAD

**Issue by Oshioke-Salaki** [BlockheaderWeb3-Community/autoswappr-dapp#6]
Implement a pixel perfect select percentage page from the [FIGMA](https://www.figma.com/design/JW1DKwDBVJq97whSwlWDLS/Auto-swapper?node-id=282-1715&node-type=frame&t=tMxPcYhV9Bd5SNnM-0) design.

**Comment by 0xdevcollins** [comment]
Can I take this issue?

**Comment by josephchimebuka** [comment]
Hello I am Joseph I am a frontend developer and blockchain developer and I am also an active contributor here on only dust here is my profile https://app.onlydust.com/u/josephchimebuka. This is my first time to contribute to this repo ill appreciate the opportunity to contribute. this is a couple of frontend and blockchain projects i have built https://metacrypt.vercel.app/ https://mattedsgn.com/
May I pick this up?

**Comment by abdegenius** [comment]
@Oshioke-Salaki made a PR please review
