### ISSUE TITLE
Duplicate Assets in Public Directory

### ISSUE THREAD

**Issue by Abeeujah** [BlockheaderWeb3-Community/autoswappr-dapp#61]
The public directory currently contains duplicate assets, which leads to unnecessary bloat. Having multiple copies of the same asset increases project size and may introduce inconsistencies.

**Tasks:**

1. Identify and remove all duplicate assets in the `public` directory.
2. Ensure that each asset has a single entry in the directory.
3. Only store assets in the `public` directory when absolutely necessary, as it directly impacts page weight.
4. Move the exports in the `svgs` directory to the `assets` directory to enhance maintainability.

**Optimization Suggestion:**

- Export assets as SVG files and convert them to React components. This ensures they are parsed and built alongside the page's HTML, improving SEO and performance.
- By eliminating redundant network requests for assets, this will also enhance the Largest Contentful Paint (LCP) metric.

**Expected Outcome:**
- Reduced project size and improved maintainability.
- Better page load performance and SEO ranking.

**Reference:**
- [PageSpeed Insights](https://developers.google.com/speed/docs/insights/v5/about)

**ETA**
This issue is expected to be completed within 2 days of assignment. Failure to create a pull request (or draft pull request) within the expected time will lead to being unassigned.

**Comment by Supa-mega** [comment]
Mind if I try this one? FIRST TIME contributor  with extensive  knowledge in HTML , CSS ,JAVASCRIPT and more ...ETA 24HOURS

**Comment by Amarjeet325** [comment]
Let me handle this issue!

**Comment by blessingbytes** [comment]
i would love to work on this task

**Comment by Pvsaint** [comment]
May I take care of this?
If it's still available, I'm a front-end developer proficient in react and next js, I'll like to contribute to the proj5

**Comment by BrunoAmbricca** [comment]
I would like to work on this issue

**Comment by Yunusabdul38** [comment]
I’d like to work on this.

**Comment by anonfedora** [comment]
Hi, I'm anonfedora a fullstack Blockchain developer, proficient in Cairo, Rust, Nextjs, Nestjs.

**Comment by emarc99** [comment]
Can I jump on this task? ETA - 2 day

**Comment by Jagadeeshftw** [comment]
I'd like to handle this task.

**Comment by 1nonlypiece** [comment]
May I take this issue on?

**Comment by DanielEmmanuel1** [comment]
I’d like to resolve this.

Good day my name is Deon and I'm a Web3 developer and will like to take up this issue. \

How i hope to tackle and soleve the issue
- I would first identify what pages are static and which ones are dynamic.
- For static pages I would make a list of suitable titles and descriptions.
- For dynamic pages I would generate metadata using either params or search params.
- Lastly I would find suitable images  to help with Open graph for social media sharing.

I am a first time contributor to the project and would love to contribute if given the opportunity.

**Comment by ekumamatthew** [comment]
Can I attempt this issue?

**Comment by akintola4** [comment]
Can I try solving this issue?

**Comment by Michaelkingsdev** [comment]
Could I take a shot at this?

**Comment by mimisavage** [comment]
Can I jump on this task?

**Comment by caxtonacollins** [comment]
I am a Full Stack Developer with two years of professional experience, specializing in web3. I have strong background in blockchain and extensive experience in Next.js/React, TypeScript, Rust and Cairo.

I will like to take care of this.

**Comment by BigBen-7** [comment]
can this be assigned to me?

**Comment by emmz3230** [comment]
I’d like to resolve this.
I will create an index file image and import all the images and make them exportable.

example
import image from '../assets/[image name]

export  {image , any other image } as default

not well written though 
delete all duplicate images in the asset folder and move tot the public directory for better seo performance

**Comment by Ibinola** [comment]
Can I start working on this?
