### ISSUE TITLE
Missing or Inadequate Site Metadata

### ISSUE THREAD

**Issue by Abeeujah** [BlockheaderWeb3-Community/autoswappr-dapp#62]
The application is currently using the default metadata provided by Next.js during initialization. This is suboptimal for SEO, as web crawlers cannot properly index the pages.

**Tasks:**
- Create and configure meaningful metadata for each page in the application.
- Include key metadata fields like title, description, Open Graph (OG) tags, and Twitter Card metadata to improve search engine indexing and social sharing.

**Expected Outcome:**
- Improved SEO and search engine visibility for the application.
- Enhanced social media link previews for better user engagement.

**Reference:**
- [Optimizing Metadata](https://nextjs.org/docs/app/building-your-application/optimizing/metadata)

**ETA**
This issue is expected to be completed within 2 days of assignment. Failure to create a pull request (or draft pull request) within the expected time will lead to being unassigned.

**Comment by Supa-mega** [comment]
May I pick this up? if its still available .. ETA 24HRS

**Comment by Amarjeet325** [comment]
Hi , I am a full stack developer is a versatile professional skilled in both front-end and back-end development, capable of designing user interfaces, building robust server-side applications, and managing databases.  
Can I take this from here?  Thank you !

**Comment by blessingbytes** [comment]
Can I take this up

**Comment by Pvsaint** [comment]
May I take care of this?
If it's still available, I'm a front-end developer proficient in react and next js

**Comment by BrunoAmbricca** [comment]
I would like to work on this issue

**Comment by Yunusabdul38** [comment]
Can I handle this task?

**Comment by emarc99** [comment]
Is it okay if I tackle this?
ETA - 2 days

**Comment by Jagadeeshftw** [comment]
Could I take on this issue?

**Comment by 1nonlypiece** [comment]
I'd love to give this a go.

**Comment by ekumamatthew** [comment]
Could I take over this issue? I am an experienced react/next js frontend developer.

**Comment by Michaelkingsdev** [comment]
Can I handle this task?

**Comment by caxtonacollins** [comment]
I am a Full Stack Developer with two years of professional experience, specializing in web3. I have strong background in blockchain and extensive experience in Next.js/React, TypeScript, Rust and Cairo.

I will like to take care of this.

**Comment by emmz3230** [comment]
Could I try solving this?
changing the metadata to index for seo optimisation like title in their respective section or better still call it tags or element as desire and will tell maintainer progress on it when assigned the task

**Comment by Ibinola** [comment]
I’d like to work on this.

**Comment by jaykayudo** [comment]
Can i be assigned this?
ETA - 1 day

**Comment by leevigh** [comment]
Hi everyone!, I'm a Web3Bridge member
I’d be happy to work on optimizing the SEO for this app. With over 4 years of experience in frontend development, I’ve taken Google digital skills courses, including SEO optimization, and I've volunteered to optimize SEO on some Next.js projects.

Estimated time: 1-2 days

How I’ll approach it:
Create description metadata copy from information I gather about the application and the value it offers and carry out some keyword research on Google Keyword Planner and AnswerThePublic to better optimize the metadata description.
Include the correct links to social media sites.
I'll add the necessary informative Open graph metadata  to ensure consistency when site links are shared to other platforms.

Let me know if I can start working on this!

**Comment by Agbeleshe** [comment]
Can I attempt this issue?
ETA: 8hrs

**Comment by Luluameh** [comment]
I’d love to work on this task.

**Comment by davedumto** [comment]
Hi,
My name is David, and I am a frontend developer skilled in React.js, TypeScript, JavaScript and Next.js, with experience in SEO optimization. I am excited to take on the task of improving metadata for the application to enhance SEO and social media link previews.
I will create meaningful metadata for each page, including fields like titles, descriptions, OG tags, and Twitter Card metadata. ETA 2 Days

**Comment by Ekene001** [comment]
Can I take this from here?

**Comment by jahrulezfrancis** [comment]
I'm interested in this task and would love to contribute to improving the application’s SEO and social sharing by configuring meaningful metadata for its pages. My approach will include setting custom titles, descriptions, Open Graph tags, and Twitter Card metadata tailored to each page.

With experience in optimizing metadata for SEO and enhancing social media previews, I’m confident I can achieve the expected outcomes of better search engine visibility and engagement. 

I can have it ready within 12 to 24 hours

**Comment by Benjtalkshow** [comment]
Can I take this from here?

**Comment by ryzen-xp** [comment]
Let me handle this issue!

**Comment by wheval** [comment]
Hello @Abeeujah, I'm Wheval an experienced Frontend Developer and serial contributor on Onlydust.

I am interested in fixing this.
I would use the Nextjs Metadata API to configure the metadata for each page.
I would also use SEMRush and Google Keyword Planner to optimize keywords relevant to each page in the Metadata for better SEO and site indexing.
I would ensure to include Open Graph (OG) tags and Twitter Card metadata for enhanced link previews.

ETA is 2 days.

**Comment by tosinmoses384** [comment]
Could I take over this issue?  

I am a Senior software engineer(FE-heavy) with 8 years of experience building both web and mobile applications.

I will approach the given task in the following steps:

1. I will identify metadata: I will first determine the key metadata fields

2. I will then check and install the necessary packages if missing 

3. Create a metadata configuration if needed.

4. Implement metadata in each page, repeat for other pages and also test SEO.

Thank you

**Comment by ONEONUORA** [comment]
Can I take this issue? I am a full stack and blockchain developer
