### ISSUE TITLE
Social links in documentation page

### ISSUE THREAD

**Issue by Abeeujah** [BlockheaderWeb3-Community/autoswappr-dapp#73]
Currently in the documentation page in `app/documentation/Contact.tsx` The social links are missing, add the following links to help users reach the appropriate media channel.

change
```html
<ol className="list-decimal text-[#D2CED8CC] pl-4">
        <li>Discord: Join Here</li>
        <li>Telegram: Join Here</li>
</ol>
```

to
```html
<ol className="list-decimal text-[#D2CED8CC] pl-4">
        <li>
          Twitter: <a href="https://twitter.com/auto_swappr">Join Here</a>
        </li>
        <li>
          Telegram: <a href="https://t.co/yFNm0juRkX">Join Here</a>
        </li>
 </ol>
```

**Comment by Joewizy** [comment]
Could I be assigned to this?

**Comment by GoSTEAN** [comment]
I'd like to handle this task. I am full stack developer

**Comment by Birdmannn** [comment]
Please can I handle this task? I am a new contributor and I would want to build my profile

**Comment by ryzen-xp** [comment]
Hi, I am proficient Blockchain developer  expert in Cairo , Rust and Solidity  and also in web development.
I have  contributed many cairo ,rust  projects like chainevents , arkprojects sunshine etc  .   please /assign  this issue .
Thank You

**Comment by OWK50GA** [comment]
Can I try solving this issue?
Hi, I'm a proficient Frontend Web Developer, and my github and OnlyDust profiles are there to attest to that fact.

I'll love it if given the chance to contribute in this small way to Autoswappr.
ETA - 2 hours

**Comment by sonkeydotcom** [comment]
Can I contribute to this one?

**Comment by 3th-Enjay** [comment]
I’d like to work on this.

**Comment by Yunusabdul38** [comment]
Mind if I take this issue?
