### ISSUE TITLE
Implement DEX swapper page

### ISSUE THREAD

**Issue by Oshioke-Salaki** [BlockheaderWeb3-Community/autoswappr-dapp#8]
Implement a pixel perfect DEX swapper page from the [FIGMA](https://www.figma.com/design/JW1DKwDBVJq97whSwlWDLS/Auto-swapper?node-id=282-1715&node-type=frame&t=tMxPcYhV9Bd5SNnM-0) design.

**Comment by Yunusabdul38** [comment]
I'd like to work on this issue.
and make sure it meets the requirements

**Comment by josephchimebuka** [comment]
Hello I am Joseph I am a frontend developer and blockchain developer and I am also an active contributor here on only dust here is my profile https://app.onlydust.com/u/josephchimebuka. This is my first time to contribute to this repo ill appreciate the opportunity to contribute. this is a couple of frontend and blockchain projects i have built https://metacrypt.vercel.app/ https://mattedsgn.com/
May I pick this up?

**Comment by anonfedora** [comment]
Hi I'm Eleazar, a fullstack Blockchain developer, I can implement that.

**Comment by BrunoAmbricca** [comment]
I would like to work on this issue

**Comment by abdegenius** [comment]
I'd love to give this a go. I can comfortably handle this issues

**Comment by martinvibes** [comment]
Can I take care of this issue?
i'm a frontend dev and a blockchain dev please kindly assign :)

**Comment by Akshola00** [comment]
I'd love to work on this!

**Comment by zintarh** [comment]
Can I tackle this one?

**Comment by CollinsC1O** [comment]
I'd love to work on this!

**Comment by caxtonacollins** [comment]
please i would love to tackle this!

**Comment by JoE11-y** [comment]
Could I take a shot at this?

**Comment by ShantelPeters** [comment]
I'd love to give this a go.

**Comment by Kaminar-i** [comment]
Can I take on this issue?

**Comment by DanielEmmanuel1** [comment]
Can I handle this task?
I'm a frontend developer with sufficient experience in creating a pixel perfect UI replica
ETA: 48 hrs
