### ISSUE TITLE
Implement DEX swapper history page

### ISSUE THREAD

**Issue by Oshioke-Salaki** [BlockheaderWeb3-Community/autoswappr-dapp#9]
Implement a pixel perfect DEX swapper history page from the [FIGMA](https://www.figma.com/design/JW1DKwDBVJq97whSwlWDLS/Auto-swapper?node-id=282-1715&node-type=frame&t=tMxPcYhV9Bd5SNnM-0) design.

**Comment by Yunusabdul38** [comment]
I'd like work on this issue.
and make sure it meets the requirements

**Comment by 0xdevcollins** [comment]
Can I attempt this issue?

**Comment by Akshola00** [comment]
Can I start working on this?

**Comment by abdegenius** [comment]
I'd love to work on this!I can comfortably handle this issues

**Comment by Benjtalkshow** [comment]
I'd like to handle this task. 
I am a Full Stack Developer with a strong background in blockchain and extensive experience in Next.js/React, TypeScript, and Rust. I’ve made over 45 contributions to over 15 projects in the OnlyDust ecosystem, solving complex issues and delivering efficient, scalable solutions.

MY ETA is 48hrs. Thanks

**Comment by martinvibes** [comment]
Can I take care of this issue?
i'm a frontend dev and a blockchain dev kindly assign :)

**Comment by Yunusabdul38** [comment]
I'd love to work on this issue.
and make sure it meets the requirements
